//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "approveAchievement", namespace = "http://service.achievement.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "approveAchievement", namespace = "http://service.achievement.ibm.com/", propOrder = {
    "achievementId",
    "status",
    "category",
    "pointValue",
    "approverComment"
})
public class ApproveAchievement {

    @XmlElement(name = "achievementId", namespace = "")
    private String achievementId;
    @XmlElement(name = "status", namespace = "")
    private String status;
    @XmlElement(name = "category", namespace = "")
    private String category;
    @XmlElement(name = "pointValue", namespace = "")
    private int pointValue;
    @XmlElement(name = "approverComment", namespace = "")
    private String approverComment;

    /**
     * 
     * @return
     *     returns String
     */
    public String getAchievementId() {
        return this.achievementId;
    }

    /**
     * 
     * @param achievementId
     *     the value for the achievementId property
     */
    public void setAchievementId(String achievementId) {
        this.achievementId = achievementId;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * 
     * @param status
     *     the value for the status property
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * 
     * @param category
     *     the value for the category property
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * 
     * @return
     *     returns int
     */
    public int getPointValue() {
        return this.pointValue;
    }

    /**
     * 
     * @param pointValue
     *     the value for the pointValue property
     */
    public void setPointValue(int pointValue) {
        this.pointValue = pointValue;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getApproverComment() {
        return this.approverComment;
    }

    /**
     * 
     * @param approverComment
     *     the value for the approverComment property
     */
    public void setApproverComment(String approverComment) {
        this.approverComment = approverComment;
    }

}
