//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "findEmployees", namespace = "http://service.achievement.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findEmployees", namespace = "http://service.achievement.ibm.com/", propOrder = {
    "emailID",
    "firstName",
    "lastName",
    "managerFlag"
})
public class FindEmployees {

    @XmlElement(name = "emailID", namespace = "")
    private String emailID;
    @XmlElement(name = "firstName", namespace = "")
    private String firstName;
    @XmlElement(name = "lastName", namespace = "")
    private String lastName;
    @XmlElement(name = "managerFlag", namespace = "")
    private String managerFlag;

    /**
     * 
     * @return
     *     returns String
     */
    public String getEmailID() {
        return this.emailID;
    }

    /**
     * 
     * @param emailID
     *     the value for the emailID property
     */
    public void setEmailID(String emailID) {
        this.emailID = emailID;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * 
     * @param firstName
     *     the value for the firstName property
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * 
     * @param lastName
     *     the value for the lastName property
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * 
     * @return
     *     returns String
     */
    public String getManagerFlag() {
        return this.managerFlag;
    }

    /**
     * 
     * @param managerFlag
     *     the value for the managerFlag property
     */
    public void setManagerFlag(String managerFlag) {
        this.managerFlag = managerFlag;
    }

}
