//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "findAchievementByApproverID", namespace = "http://service.achievement.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAchievementByApproverID", namespace = "http://service.achievement.ibm.com/")
public class FindAchievementByApproverID {

    @XmlElement(name = "approverId", namespace = "")
    private String approverId;

    /**
     * 
     * @return
     *     returns String
     */
    public String getApproverId() {
        return this.approverId;
    }

    /**
     * 
     * @param approverId
     *     the value for the approverId property
     */
    public void setApproverId(String approverId) {
        this.approverId = approverId;
    }

}
