//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "findEmployeesByEmailID", namespace = "http://service.achievement.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findEmployeesByEmailID", namespace = "http://service.achievement.ibm.com/")
public class FindEmployeesByEmailID {

    @XmlElement(name = "emailID", namespace = "")
    private String emailID;

    /**
     * 
     * @return
     *     returns String
     */
    public String getEmailID() {
        return this.emailID;
    }

    /**
     * 
     * @param emailID
     *     the value for the emailID property
     */
    public void setEmailID(String emailID) {
        this.emailID = emailID;
    }

}
