//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "findEmployeesByID", namespace = "http://service.achievement.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findEmployeesByID", namespace = "http://service.achievement.ibm.com/")
public class FindEmployeesByID {

    @XmlElement(name = "empID", namespace = "")
    private String empID;

    /**
     * 
     * @return
     *     returns String
     */
    public String getEmpID() {
        return this.empID;
    }

    /**
     * 
     * @param empID
     *     the value for the empID property
     */
    public void setEmpID(String empID) {
        this.empID = empID;
    }

}
