//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "findAchievementType", namespace = "http://service.achievement.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findAchievementType", namespace = "http://service.achievement.ibm.com/")
public class FindAchievementType {

    @XmlElement(name = "typeId", namespace = "")
    private String typeId;

    /**
     * 
     * @return
     *     returns String
     */
    public String getTypeId() {
        return this.typeId;
    }

    /**
     * 
     * @param typeId
     *     the value for the typeId property
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

}
