//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.ibm.achievement.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

@XmlRootElement(name = "registerEmployee", namespace = "http://service.achievement.ibm.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "registerEmployee", namespace = "http://service.achievement.ibm.com/")
public class RegisterEmployee {

    @XmlElement(name = "employeeVO", namespace = "")
    private com.ibm.achievement.entity.EmployeeVO employeeVO;

    /**
     * 
     * @return
     *     returns EmployeeVO
     */
    public com.ibm.achievement.entity.EmployeeVO getEmployeeVO() {
        return this.employeeVO;
    }

    /**
     * 
     * @param employeeVO
     *     the value for the employeeVO property
     */
    public void setEmployeeVO(com.ibm.achievement.entity.EmployeeVO employeeVO) {
        this.employeeVO = employeeVO;
    }

}
